import {
    CheckCircle2,
    Ticket,
    Sparkles,
    Users,
    Mic2,
    Wrench,
    Presentation,
    RadioTower,
    MessageSquare,
    Trophy,
    Star,
    Flag,
    MapPin,
    Clock,
    CalendarDays,
    ZoomIn,
    X,
    ArrowLeft,
    LayoutList,
    LayoutGrid,
    Timer,
    Target,
    Shield,
    Plus,
    Trash2,
    UserCircle,
    Eye,
    Swords,
    ExternalLink,
    Heart,
    Image as ImageIcon,
    ChevronUp,
    Briefcase,
    Download,
    LogOut,
    Search,
    AlertCircle,
    Globe,
    type LucideIcon,
} from "lucide-react";

import { AgendaItem, SpeakerType, Team, TeamMember, TimelineNode, TimelineStatus } from "@/app/agenda/_utils/agenda_types";

/* ─── AGENDA DATA ─── */
export const agendaItems: AgendaItem[] = [
    {
        id: 1,
        time: "7:30 AM",
        endTime: "8:00 AM",
        duration: "30 min",
        title: "Pre-event Setup",
        description: "Pre-event setup and final checks before the event starts!",
        location: "Main Venue",
        icon: CheckCircle2,
        color: "bg-emerald-500",
        shadow: "shadow-emerald-500/30",
        category: "Setup",
        status: "upcoming",
    },
    {
        id: 2,
        time: "8:00 AM",
        endTime: "9:00 AM",
        duration: "1 hour",
        title: "Registrations & Activities",
        description: "Registrations open, side activities setup and open to all attendees.",
        location: "Main Entrance",
        icon: Ticket,
        color: "bg-blue-500",
        shadow: "shadow-blue-500/30",
        category: "Registration",
        status: "upcoming",
    },
    {
        id: 3,
        time: "9:00 AM",
        endTime: "9:15 AM",
        duration: "15 min",
        title: "Opening Ceremony",
        description: "Opening ceremony commences to kick off MedEngineers 2026.",
        location: "MAIN AUDITORIUM",
        icon: Sparkles,
        color: "bg-purple-500",
        shadow: "shadow-purple-500/30",
        category: "Ceremony",
        status: "upcoming",
    },
    {
        id: 4,
        time: "9:15 AM",
        endTime: "9:45 AM",
        duration: "30 min",
        title: "Team Formation & Festival",
        description: "Teams start working together to decide upon a topic for their presentation. Meanwhile, activities, sponsor booths, food stalls and the club stall (festival) begin.",
        location: "MAIN BUILDING ROTUNDA & MAIN PLAZA",
        icon: Users,
        color: "bg-amber-500",
        shadow: "shadow-amber-500/30",
        category: "Activity",
        status: "upcoming",
    },
    {
        id: 5,
        time: "10:00 AM",
        endTime: "2:00 PM",
        duration: "4 hours",
        title: "Sponsor Keynotes",
        description: "Keynote speeches from sponsors commence, with live updates and tracking on our official website, organized through timeslots.",
        location: "MAIN AUDITORIUM + HALL A & B",
        icon: Mic2,
        color: "bg-indigo-500",
        shadow: "shadow-indigo-500/30",
        category: "Keynote",
        status: "upcoming",
    },
    {
        id: 6,
        time: "12:00 PM",
        endTime: "12:30 PM",
        duration: "30 min",
        title: "Prototyping Mentorship",
        description: "Mentorship period in collaboration with IEEE for 25 prototyping teams for guidance purposes. These teams work in individual classrooms.",
        location: "ENGINEERING BUILDING",
        icon: Wrench,
        color: "bg-pink-500",
        shadow: "shadow-pink-500/30",
        category: "Workshop",
        status: "upcoming",
    },
    {
        id: 7,
        time: "12:30 PM",
        endTime: "2:00 PM",
        duration: "1.5 hours",
        title: "Poster Concept Mentorship",
        description: "Mentorship period in collaboration with IEEE for 75 teams for guidance on their posters and concepts.",
        location: "MAIN BUILDING ROTUNDA",
        icon: Presentation,
        color: "bg-rose-500",
        shadow: "shadow-rose-500/30",
        category: "Workshop",
        status: "upcoming",
    },
    {
        id: 8,
        time: "2:00 PM",
        endTime: "3:00 PM",
        duration: "1 hour",
        title: "Keynote Speeches",
        description: "Keynote speeches continue for all participants.",
        location: "MAIN AUDITORIUM",
        icon: RadioTower,
        color: "bg-sky-500",
        shadow: "shadow-sky-500/30",
        category: "Keynote",
        status: "upcoming",
    },
    {
        id: 9,
        time: "3:00 PM",
        endTime: "4:00 PM",
        duration: "1 hour",
        title: "Panel Discussion",
        description: "Panel discussion commences, speakers get 10 minutes each (8 minutes for speeches + 2 for Q/A).",
        location: "MAIN AUDITORIUM",
        icon: MessageSquare,
        color: "bg-cyan-500",
        shadow: "shadow-cyan-500/30",
        category: "Discussion",
        status: "upcoming",
    },
    {
        id: 10,
        time: "4:00 PM",
        endTime: "6:30 PM",
        duration: "2.5 hours",
        title: "Presentations & Pitching",
        description: "All 100 teams submit their presentations, prototype development time ends. Pitching in the MAIN AUDITORIUM for the 25 prototyping teams begins, and the other 75 teams present their posters. Festival continues until 7:30 PM.",
        location: "MAIN AUDITORIUM / MAIN PLAZA",
        icon: Trophy,
        color: "bg-yellow-500",
        shadow: "shadow-yellow-500/30",
        category: "Presentation",
        status: "upcoming",
    },
    {
        id: 11,
        time: "6:30 PM",
        endTime: "7:00 PM",
        duration: "30 min",
        title: "Awards & Closing Ceremony",
        description: "Awards ceremony, followed by the closing ceremony, and a final event group picture.",
        location: "MAIN AUDITORIUM",
        icon: Star,
        color: "bg-purple-600",
        shadow: "shadow-purple-600/30",
        category: "Ceremony",
        status: "upcoming",
    },
    {
        id: 12,
        time: "7:00 PM",
        endTime: "",
        duration: "",
        title: "Event Concludes",
        description: "Participants exit, cleanup begins, event ends!",
        location: "Main Exit",
        icon: Flag,
        color: "bg-slate-500",
        shadow: "shadow-slate-500/30",
        category: "Closing",
        status: "upcoming",
    }
];

/* ─── TIMELINE NODES ─── */
export const timelineNodes: TimelineNode[] = [
    { time: "8AM", label: "Doors Open", status: "upcoming" },
    { time: "9AM", label: "Opening Ceremony", status: "upcoming" },
    { time: "10AM", label: "Sponsor Keynotes", status: "upcoming" },
    { time: "12PM", label: "Mentorship", status: "upcoming" },
    { time: "3PM", label: "Panel Discussion", status: "upcoming" },
    { time: "4PM", label: "Presentations", status: "upcoming" },
    { time: "7PM", label: "Closing", status: "upcoming" },
];

/* ─── CATEGORY COLORS ─── */
export const categoryColors: Record<string, string> = {
    Setup: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
    Registration: "text-blue-400 bg-blue-400/10 border-blue-400/20",
    Ceremony: "text-purple-400 bg-purple-400/10 border-purple-400/20",
    Activity: "text-amber-400 bg-amber-400/10 border-amber-400/20",
    Keynote: "text-indigo-400 bg-indigo-400/10 border-indigo-400/20",
    Workshop: "text-pink-400 bg-pink-400/10 border-pink-400/20",
    Discussion: "text-cyan-400 bg-cyan-400/10 border-cyan-400/20",
    Presentation: "text-yellow-400 bg-yellow-400/10 border-yellow-400/20",
    Closing: "text-slate-400 bg-slate-400/10 border-slate-400/20",
};

/* ─── TEAM COLORS (avatar) ─── */
export const TEAM_COLORS = [
    "bg-blue-500/20 text-blue-400",
    "bg-emerald-500/20 text-emerald-400",
    "bg-purple-500/20 text-purple-400",
    "bg-[#007b8a]/20 text-[#007b8a]",
    "bg-red-500/20 text-red-400",
    "bg-cyan-500/20 text-cyan-400",
    "bg-orange-500/20 text-orange-400",
    "bg-green-500/20 text-green-400",
];